// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/nafsam-videos/Album.tsx": () => import("../components/mockups/nafsam-videos/Album.tsx"),
  "./components/mockups/nafsam-videos/Cinema.tsx": () => import("../components/mockups/nafsam-videos/Cinema.tsx"),
  "./components/mockups/nafsam-videos/Current.tsx": () => import("../components/mockups/nafsam-videos/Current.tsx"),
  "./components/mockups/nafsam-videos/Journal.tsx": () => import("../components/mockups/nafsam-videos/Journal.tsx")
};
